### ISSUE TITLE
Calculate Hz for the vertical magnetic dipole source

### ISSUE THREAD

**Issue by adam-sim-dev** [emsig/empymod#124]
Hello, @prisae ,

I use the following code to calculate component 66. I expect the result to be the magnetic field Hz for the vertical magnetic dipole source. However, when I compare the result with the analytical solution, I found it is not. Can you guide me how to do this?

Thanks,
Adam

```
import empymod
import numpy as np
# source: x, y, z
src = [0, 0, 0.0]
# receiver: x, y, z
rec = [100.0, 0.0, 0.0]
# layer boundaries
depth = [0, 2000]
# layer resistivities
res = [1e20, 100, 100]
# frequency
freq = 1.0e-3
# signal
signal = None
# component
ab = 66
# Compute the electric field due to a magnetic source at 1.0e-3 Hz.
EMfield = empymod.dipole(src, rec, depth, res, freq, signal, ab, verb=4, xdirect=True)
# Calculate B
# EMfield = EMfield*(4.0*3.141592653*1.0e-7)

print(EMfield)
```

**Comment by prisae** [comment]
Hi @adam-sim-dev ,

I am currently on holiday, I will be back at work next week. So I did not (yet) run your example. What is the result of it, and what would you expect instead?

Have you seen the example https://empymod.readthedocs.io/en/stable/examples/reproducing/ward1988.html - this is along the lines of what you try to do, right?
