### ISSUE TITLE
Ward example (Figure 4.8): How to calculate anisotropic responses

### ISSUE THREAD

**Issue by CHDtdem** [emsig/empymod#125]
Hi @prisae 

I am going through the Ward example you gave in the Examples section of the documentation. The following code is basically what you have in the examples except that I have added several lines to try to calculate the hypothetical anisotropic responses. However, I do not think I saw anything different with the aniso parameter being specified according to the plotted figure. Could you please take a look at it and let me know what I did wrong?

```python
#!/usr/bin/env python3

import empymod
import numpy as np
from scipy.special import erf
import matplotlib.pyplot as plt
from scipy.constants import mu_0

eperm = [0, 0]  # Reduce early time numerical noise (diffusive approx for air)

# Survey parameters
radius = 50
area = radius**2*np.pi
time = np.logspace(-7, -1, 301)
src = [radius, 0, 0, 90, 0]
rec = [0, 0, 0, 0, 90]
depth = 0
res = [2e14, 100]
strength = area/(radius/2)
mrec = True

# Computation
inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'strength': strength, 'mrec': mrec,
       'epermH': eperm, 'verb': 1}

fhz_num = empymod.bipole(signal=-1, **inp)
fdhz_num = empymod.bipole(signal=0, **inp)

aniso = [10, 10]
inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'strength': strength, 'mrec': mrec,
       'epermH': eperm, 'verb': 1, 'aniso': aniso}

fhz_aniso_num = empymod.bipole(signal=-1, **inp)
fdhz_aniso_num = empymod.bipole(signal=0, **inp)

# Figure
plt.figure(figsize=(4, 6))

ax1 = plt.subplot(111)
plt.plot(time*1e3, fdhz_num, 'C0-', label=r'dhz/dt (A/m-s)')
plt.plot(time*1e3, fdhz_aniso_num, 'C0--', label=r'dhz/dt aniso (A/m-s)',
         linewidth=2)
plt.plot(time*1e3, -fdhz_num, 'C0--')

plt.plot(time*1e3, fhz_num, 'C1-', label='hz (A/m)')
plt.plot(time*1e3, fhz_aniso_num, 'C1--', label='hz aniso (A/m)', linewidth=2)
plt.plot(time*1e3, -fhz_num, 'C1--')

plt.xscale('log')
plt.yscale('log')
plt.xlim([1e-4, 1e2])
plt.yticks(10**np.arange(-7., 4))
plt.ylim([1e-7, 5e3])

plt.xlabel('time (ms)')
plt.legend()

plt.tight_layout()
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/7824380/118200362-78ea0f80-b42f-11eb-9e4c-55cbf84e2581.png)

**Comment by prisae** [comment]
Hi @CHDtdem,

The code you posted looks correct (I am on holiday, so I haven't tested it, I am just replying from looking at your code). So there are two possibilities;
1. The chosen acquisition setup is not sensitive to anisotropy;
2. There is a bug in empymod.

Now while (2.) is always possible of course (I do not claim at all that empymod is free of bugs, no code is), I think here it is rather (1.). The chosen setup has zero vertical distance between source and receiver, and you measure the vertical magnetic field. I haven't tested it myself, but it is likely that this setup is only sensitive to horizontal resistivity.

**Comment by CHDtdem** [comment]
Thanks very much for your comment. I actually also thought about this and suspected the particular survey configuration is not sensitive to vertical conductivity. The thing that I do not know much about is how the code sets up the conductivity tensor. Being a 1D code, it only makes sense to have different horizontal and vertical conductivities, as what you are doing to control the ratio between rho_v/rho_h. But which one does it change? There is the resistivity input of 100 \Omega m, after specifying the aniso parameter, is rho_v got changed, or is rho_h got changed? If what you said in 1 is correct, i.e., the configuration is not sensitive to the conductivity anisotropy, then it would be rho_v got changed?

**Comment by CHDtdem** [comment]
Okay, here is another quick verification. I specified the anisotropy parameter in the code used to calculate Figure 4.4:

```python
#!/usr/bin/env python3

import empymod
import numpy as np
from scipy.special import erf
import matplotlib.pyplot as plt
from scipy.constants import mu_0

def hz(t, res, r, m=1.):
    r"""Return equation 4.69a, Ward and Hohmann, 1988.

    Switch-off response (i.e., Hz(t)) of a homogeneous isotropic half-space,
    where the vertical magnetic source and receiver are at the interface.

    Parameters
    ----------
    t : array
        Times (t)
    res : float
        Halfspace resistivity (Ohm.m)
    r : float
        Offset (m)
    m : float, optional
        Magnetic moment, default is 1.

    Returns
    -------
    hz : array
        Vertical magnetic field (A/m)

    """
    theta = np.sqrt(mu_0/(4*res*t))
    theta_r = theta*r

    s = -(9/theta_r+4*theta_r)*np.exp(-theta_r**2)/np.sqrt(np.pi)
    s += erf(theta_r)*(9/(2*theta_r**2)-1)
    s *= m/(4*np.pi*r**3)

    return s

def dhzdt(t, res, r, m=1.):
    r"""Return equation 4.70, Ward and Hohmann, 1988.

    Impulse response (i.e., dHz(t)/dt) of a homogeneous isotropic half-space,
    where the vertical magnetic source and receiver are at the interface.

    Parameters
    ----------
    t : array
        Times (t)
    res : float
        Halfspace resistivity (Ohm.m)
    r : float
        Offset (m)
    m : float, optional
        Magnetic moment, default is 1.

    Returns
    -------
    dhz : array
        Time-derivative of the vertical magnetic field (A/m/s)

    """
    theta = np.sqrt(mu_0/(4*res*t))
    theta_r = theta*r

    s = (9 + 6 * theta_r**2 + 4 * theta_r**4) * np.exp(-theta_r**2)
    s *= -2 * theta_r / np.sqrt(np.pi)
    s += 9 * erf(theta_r)
    s *= -(m*res)/(2*np.pi*mu_0*r**5)

    return s

time = np.logspace(-8, 0, 301)

src = [0, 0, 0, 0, 90]
rec = [100, 0, 0, 0, 90]
depth = 0
res = [2e14, 100]

hz_ana = hz(time, res[1], rec[0])
dhz_ana = dhzdt(time, res[1], rec[0])

eperm = [0, 0]  # Reduce early time numerical noise (diffusive approx for air)
aniso = [100, 100]

inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'verb': 1, 'xdirect': True, 'epermH': eperm}
hz_num = empymod.loop(signal=-1, **inp)
dhz_num = empymod.loop(signal=0, **inp)

inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'verb': 1, 'xdirect': True, 'epermH': eperm,
       'aniso': aniso}
hz_anisotropy_num = empymod.loop(signal=-1, **inp)
dhz_anisotropy_num = empymod.loop(signal=0, **inp)

plt.figure(figsize=(5, 6))

plt.plot(time*1e3, abs(dhz_ana), 'k-', lw=2, label='Ward & Hohmann')
plt.plot(time*1e3, dhz_num, 'C1-', label='empymod; dHz/dt')
plt.plot(time*1e3, dhz_anisotropy_num, color='forestgreen',
         label='empymod (anisotropy); dHz/dt')
plt.plot(time*1e3, -dhz_num, 'C1--')

plt.plot(time*1e3, abs(hz_ana), 'k-', lw=2)
plt.plot(time*1e3, hz_num, 'C0-', label='empymod; Hz')
plt.plot(time*1e3, hz_anisotropy_num, color='indianred',
         label='empymod (anisotropy); Hz')
plt.plot(time*1e3, -hz_num, 'C0--')

plt.xscale('log')
plt.yscale('log')
plt.xlim([1e-5, 1e3])
plt.yticks(10**np.arange(-11., 0))
plt.ylim([1e-11, 1e-1])
plt.xlabel('time (ms)')
plt.legend()

plt.show()
```

And here is what it looks like:
![Figure_4_2](https://user-images.githubusercontent.com/7824380/118321020-95418700-b4d7-11eb-92b6-111f33377802.png)

I think it is fair to say that there is little to no effect shown here from the anisotropic conductivity for this survey configuration either.

Another quick example where I have a three-layer model for the magnetic dipole:
```python
src = [0, 0, 0, 0, 90]
rec = [100, 0, 0, 0, 90]
depth = [0, 100, 200]
res = [2e14, 100, 10, 100]

hz_ana = hz(time, res[1], rec[0])
dhz_ana = dhzdt(time, res[1], rec[0])

eperm = [0, 0, 0, 0]  # Reduce early time numerical noise (diffusive approx for air)
aniso = [1, 1, 100, 1]

inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'verb': 1, 'xdirect': True, 'epermH': eperm}
hz_num = empymod.loop(signal=-1, **inp)
dhz_num = empymod.loop(signal=0, **inp)

inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'verb': 1, 'xdirect': True, 'epermH': eperm,
       'aniso': aniso}
hz_anisotropy_num = empymod.loop(signal=-1, **inp)
dhz_anisotropy_num = empymod.loop(signal=0, **inp)

plt.figure(figsize=(5, 6))

print(abs(dhz_num))
# plt.plot(time*1e3, abs(dhz_ana), 'k-', lw=2, label='Ward & Hohmann')
plt.plot(time*1e3, abs(dhz_num), color='indianred', label='empymod; dHz/dt')
plt.plot(time*1e3, abs(dhz_anisotropy_num), color='indianred',
         label='empymod (anisotropy); dHz/dt', linestyle='--', linewidth=3)
# plt.plot(time*1e3, -dhz_num, 'C1--')

# plt.plot(time*1e3, abs(hz_ana), 'k-', lw=2)
plt.plot(time*1e3, abs(hz_num), color='forestgreen', label='empymod; Hz')
plt.plot(time*1e3, abs(hz_anisotropy_num), color='forestgreen',
         label='empymod (anisotropy); Hz', linewidth=3, linestyle='--')
# plt.plot(time*1e3, -hz_num, 'C0--')

plt.xscale('log')
plt.yscale('log')
plt.xlim([1e-5, 1e3])
plt.yticks(10**np.arange(-11., 0))
plt.ylim([1e-11, 1e-1])
plt.xlabel('time (ms)')
plt.legend()

plt.show()
```

And here is the plot
![Figure_4 4](https://user-images.githubusercontent.com/7824380/118322832-53fea680-b4da-11eb-8e0d-813a1101a994.png)

**Comment by prisae** [comment]
From the docs:
https://empymod.readthedocs.io/en/stable/api/empymod.model.bipole.html
> res : array_like
>     Horizontal resistivities rho_h (Ohm.m); #res = #depth + 1.
>
> aniso : array_like, optional
>     Anisotropies lambda = sqrt(rho_v/rho_h) (-); #aniso = #res. Defaults to ones.

So yes, if you change `aniso` from the default 1 it basically changes the vertical resistivity.

**Comment by prisae** [comment]
General quick comments.

- To avoid early time numerical noise, I would only set the first value (air) of `eperm` to zero. Hence, `eperm = [0, 1, 1, 1]` in the latter example.
- You give the air an anisotropy of 100 (`aniso = [100, 100]` in the first example). This is unrealistic, but further, it will hardly have an effect. The air is simply very resistive, you will not see a big difference between 2e14 and 2e14*100^2.

Now lets take your first example (of the 2nd round): Again, you have source and receiver at the same depth, vertical z-fields. There is no influence of the vertical resistivity. For one, your signal will be dominated by the air. The air is _very_ resistive. You made it anisotropic, which is unrealistic, but it won't matter numerically. If you have 2e14 or 2e20 will not give you a significant change. 

Here an example where you can see the effect of anisotropy:
```
import empymod
import numpy as np
import matplotlib.pyplot as plt


time = np.logspace(-8, 0, 301)

src = [0, 0, 1, 40, 45]
rec = [100, 0, 10, 20, -45]
depth = 0
res = [100, 100]

eperm = [0, 1]
aniso = [1, 2]

inp = {'src': src, 'rec': rec, 'depth': depth, 'res': res,
       'freqtime': time, 'verb': 1, 'xdirect': True, 'epermH': eperm}

hz_num = empymod.loop(signal=-1, **inp)
dhz_num = empymod.loop(signal=0, **inp)

hz_anisotropy_num = empymod.loop(signal=-1, aniso=aniso, **inp)
dhz_anisotropy_num = empymod.loop(signal=0, aniso=aniso, **inp)

plt.figure(figsize=(5, 6))

plt.plot(time*1e3, abs(dhz_num), 'C0-', label='isotropic; dHz/dt')
plt.plot(time*1e3, abs(dhz_anisotropy_num), 'C2--', label='anisotropy; dHz/dt')

plt.plot(time*1e3, abs(hz_num), 'C1-', label='isotropic; Hz')
plt.plot(time*1e3, abs(hz_anisotropy_num), 'C3--', color='C2', label='anisotropic; Hz')

plt.xscale('log')
plt.yscale('log')
plt.xlabel('time (ms)')
plt.legend()

plt.show()
```

So I rotated source and receiver. I also added some vertical distance between source and receiver. The result is (the zigg-zagg part for early times of dHz/dt is numerical noise from the Fourier transform, the signal goes to zero):

![index](https://user-images.githubusercontent.com/8020943/118339023-f426f080-b517-11eb-8bca-eae209be0d05.png)

I hardly ever work with loops, so I cannot give you lots of advice. You have to make some tests (or search the literature) to see which configurations are sensitive to vertical transverse isotropy.

**Comment by prisae** [comment]
A good way to test that would be to create an entire 2D section, and draw the fieldlines. Then you could check where there are vertical currents, hence where you will have sensitivity to anisotropy.

**Comment by CHDtdem** [comment]
Oh, you are right. I think the loop source, neither the first example nor the second one would have a meaningful vertical current system for a 1D layered Earth model. Probably I need to test this using your 3D code? I have a 3D FEM code and I recently implemented the anisotropic part of it. I just want to have something to compare against! Thanks for your comments.

**Comment by prisae** [comment]
An option would be to use electric dipoles instead of loops, or vertical loops. 

You might be interested in this: https://github.com/swung-research/3d-csem-open-source-landscape

All of the examples have anisotropy.

**Comment by CHDtdem** [comment]
Yes, I think you are right. I have not worked with frequency-domain problems for ages and am a bit reluctant to get back to the frequency domain. But I guess I have to since most of the studies on anisotropy are in the frequency domain with electric sources. 

I have actually started looking at this comparison between emg3d and SimPEG: https://emsig.github.io/emg3d-gallery/gallery/comparisons/3D_triaxial_SimPEG.html.

The one you mentioned would be another good choice. I think I watched one of your talks about this comparison study and I just could not remember when and where. I might have more question later on emg3d but I guess I will start a new issue there if necessary.

Thanks very much for your comments and help!

**Comment by prisae** [comment]
An good test would be the analytical halfspace solutions implemented in `empymod.analytical`, following Slob et al, 2010, PIERS. They are available in the frequency- and in the time-domain, but only for electric sources and receivers.

You're welcome @CHDtdem - I am happy to stay in contact and to help creating a good comparison for your FEM code, just write me or open another issue, as you said. Also, feel free to write me through https://werthmuller.org/contact to exchange emails or add me on LinkedIn (https://www.linkedin.com/in/dieterwerthmuller) to stay in touch.

**Comment by prisae** [comment]
Btw, the talk you mention from AGU last year:
- https://werthmuller.org/download/research/AGU20_OpenSource3DCSEMLandscape.mp4
- https://werthmuller.org/download/research/AGU20_OpenSource3DCSEMLandscape_Presentation.pdf

**Comment by XushanLu** [comment]
Thanks very much for the links! I am working on the tri-axial anisotropy example where you compared emg3d and simpeg. I find the model is simple enough and I will move on to the Slob et al analytical example, although I probably should start from the latter one since it is analytical.
