### ISSUE TITLE
About the tilted transverse isotropy (TTI) model

### ISSUE THREAD

**Issue by liuzg-23** [emsig/empymod#154]
Hello,
Thanks very much for this software. And I want to know that if I can calculate the 1D layered model with TTI by empymod.
Zhengguang.

**Comment by prisae** [comment]
Hi @liuzg-23

No, it is not possible. empymod is based on Hunziker et al., 2015, Geophysics. It is the solution for the VTI case. If you are interested in the TTI case I recommend to have a look at Løseth and Ursin, 2007, Geophysical Journal International.
