### ISSUE TITLE
dipole() result for magnetic source or magnetic source and receiver combination

### ISSUE THREAD

**Issue by svdbaan** [emsig/empymod#157]
I tried with empymod.dipole() to reproduce the results of Figures 4.2 (p. 211) and 4.4 (p. 214) in Ward and Hohmann (1988), Electromagnetic Theory for Geophysical Applications (Nabighian ed.).

In order to get the same results as in those figures, I have to multiply, in the function dipole(), the fem() result with `-i*omega*mu0`, before tem() is called, in dipole() at line number 771 (empymod version 2.1.3):

    if ab % 10 > 3:
        # Only for magnetic sources (or magnetic source and magnetic receiver combination?)
        mu0 = 4e-7*np.pi
        omega = 2*np.pi*freq
        for col in range(EM.shape[1]):
            EM[:, col] *= -1j * omega * mu0

Is this a bug or am I doing anyhting wrong? Without the above addition, I get other results (both in frequency domain, Fig 4.2, and time domain, Fig 4.4) than in the mentioned figures.

The code to reproduce the figures:

    import numpy as np
    import matplotlib.pyplot as plt
    import empymod
    
    model = {
        'src': [0.0, 0.0, 1e-3],
        'rec': [100.0, 0.0, 1e-3],
        'depth': [0],
        'res': [1e8, 100.0],
        'ab': 66,
        'epermH': [0, 0],
        }
    
    # Figure 4.2, p. 211
    f = np.logspace(-1, 5, 241) # Hz
    Hz = empymod.dipole(freqtime=f, signal=None, **model)
    Hzre, Hzim = np.real(Hz), np.imag(Hz)
    Hzrepos, Hzreneg = np.copy(Hzre), np.copy(Hzre)
    Hzrepos[Hzre < 0] = np.nan
    Hzreneg[Hzre > 0] = np.nan
    Hzimpos, Hzimneg = np.copy(Hzim), np.copy(Hzim)
    Hzimpos[Hzim < 0] = np.nan
    Hzimneg[Hzim > 0] = np.nan
    fig = plt.figure()
    plt.plot(f, Hzrepos, 'b--', label='Real')
    plt.plot(f, -Hzreneg, 'b-')
    plt.plot(f, Hzimpos, 'r--', label='Imaginary')
    plt.plot(f, -Hzimneg, 'r-')
    plt.xlabel('f (Hz)')
    plt.ylabel('Hz (A/m)')
    plt.title('Ward and Hohmann, Figure 4.2')
    plt.legend()
    plt.xscale('log')
    plt.yscale('log')
    plt.xlim(1e-1, 1e5)
    plt.ylim(1e-12, 1e-6)
    plt.grid()
    
    # Figure 4.4, p. 214
    t = np.logspace(-8, 0, 241) # s
    hz_stepoff = empymod.dipole(freqtime=t, signal=-1, **model)
    hz_impulse = empymod.dipole(freqtime=t, signal=0, **model)
    hz_stepoffpos, hz_stepoffneg = np.copy(hz_stepoff), np.copy(hz_stepoff)
    hz_stepoffpos[hz_stepoff < 0] = np.nan
    hz_stepoffneg[hz_stepoff > 0] = np.nan
    hz_impulsepos, hz_impulseneg = np.copy(hz_impulse), np.copy(hz_impulse)
    hz_impulsepos[hz_impulse < 0] = np.nan
    hz_impulseneg[hz_impulse > 0] = np.nan
    
    fig = plt.figure()
    plt.plot(t*1e3, hz_stepoffpos, 'b-', label='hz (A/m)')
    plt.plot(t*1e3, -hz_stepoffneg, 'b--')
    plt.plot(t*1e3, hz_impulsepos, 'r-', label='dhz/dt (A/m-s)')
    plt.plot(t*1e3, -hz_impulseneg, 'r--')
    plt.xlabel('t (ms)')
    plt.title('Ward and Hohmann, Figure 4.4')
    plt.legend()
    plt.xscale('log')
    plt.yscale('log')
    plt.xlim(1e-5, 1e3)
    plt.ylim(1e-11, 1e-1)
    plt.grid()
    
    plt.show()

**Comment by prisae** [comment]
Hi @svdbaan

That is not a bug, no, but what you describe is indeed correct. The reason is that `empymod.dipole` models *dipoles*, whereas the Ward and Hohmann figures you mention are for *loops*.

The right function to use is `empymod.loop`, which is made for loops. The loop function does internally exactly what you describe, to obtain the results for loops instead of dipoles.

If you look at the manual you see that I reproduced the results you mention already with empymod: https://empymod.emsig.xyz/en/stable/gallery/reproducing/ward1988.html

I hope that helps, if not feel free to re-open the issue!

**Comment by svdbaan** [comment]
Hi Dieter,

Oh ok, I see! Thanks.



Kind regards,

Stefan van der Baan
Project leader R&D

T&A Survey │ Stefan van der Baan │ Dynamostraat 48 │ P.O. Box 20670 │ 1001 NR Amsterdam │ The Netherlands
T: +31 (0)20 665 1368 │ ***@***.******@***.***> │ www.ta-survey.nl

[2019  NL]<https://www.ta-survey.nl/>
***@***.***<https://www.linkedin.com/company/t&a-survey?trk=biz-companies-cym>[ig-logo-email]<https://www.instagram.com/tasurvey_bodemonderzoek/>

Van: Dieter Werthmüller ***@***.***>
Verzonden: woensdag 6 juli 2022 13:27
Aan: emsig/empymod ***@***.***>
CC: Stefan van der Baan ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [emsig/empymod] dipole() result for magnetic source or magnetic source and receiver combination (Issue #157)


Hi @svdbaan<https://github.com/svdbaan>

That is not a bug, no, but what you describe is indeed correct. The reason is that empymod.dipole models dipoles, whereas the Ward and Hohmann figures you mention are for loops.

The right function to use is empymod.loop, which is made for loops. The loop function does internally exactly what you describe, to obtain the results for loops instead of dipoles.

If you look at the manual you see that I reproduced the results you mention already with empymod: https://empymod.emsig.xyz/en/stable/gallery/reproducing/ward1988.html

I hope that helps, if not feel free to re-open the issue!
