### ISSUE TITLE
How to calculate other EM components

### ISSUE THREAD

**Issue by liuzg-23** [emsig/empymod#169]
Hi Dieter,
There are some problems in my code when I calculate all EM components (Ex, Ey, Ez, Hx, Hy, Hz). The following is my code:

```
import empymod
import numpy as np
import matplotlib.pyplot as plt

# x-directed bipole source: x0, x1, y0, y1, z0, z1
source = [-50, 50, 0, 0, 0, 0]
# Source frequency
frequency = 10000
# Receiver offsets
offsets = np.arange(1, 11)*500
# x-directed dipole receiver-array: x, y, z, azimuth, dip
receivers = [offsets, offsets*0, 0, 0, 0]

# Layer boundaries
depth = [0]
# Layer resistivities
resistivities = [1e20, 500]

efield = empymod.bipole(
        src=source,
        rec=receivers,
        depth=depth,
        res=resistivities,
        freqtime=frequency,
        msrc=False,
        mrec=True,
        ab=41,
        verb=4,
)

fig, ax = plt.subplots()
ax.semilogy(offsets/1e3, abs(efield.real), 'C0o-', label='|Real|')
ax.semilogy(offsets/1e3, abs(efield.imag), 'C1o-', label='|Imag|')
ax.legend()
ax.set_title('Electric field at receivers')
ax.set_xlabel('Offset (km)');
ax.set_ylabel('Electric field (V/m)')
```

Can you help me to solve this problem? Thanks very much.

Best regards,
Zhengguang.

**Comment by prisae** [comment]
Hi Zhengguang. It appears to me that you mix things from `empymod.dipole` and `empymod.bipole`. The `ab`-parameter is only for the `dipole` function. Please have a look at the relevant documentation:
- https://empymod.emsig.xyz/en/stable/api/empymod.model.dipole.html
- https://empymod.emsig.xyz/en/stable/api/empymod.model.bipole.html

So `ab=41` has no effect. It is not a problem, but you see a warning that this parameter is not used.

More importantly, the configuration you are trying to compute yields in a zero field (x-directed electric dipole measured with inline x-directed magnetic receivers), see https://empymod.emsig.xyz/en/stable/gallery/fdomain/src_rec_comparison.html : Your configuration corresponds loosely to the fourth row, first column: The field along the x-axis is zero.

**Comment by prisae** [comment]
I mark the issue as closed. Feel free to keep asking here though if it is not clear to you.

**Comment by liuzg-23** [comment]
Hi Dieter,

Thanks very much for your reply. I have another question that is how I can calculate the Hy components from empymod.bipole.

Best regards,
Zhengguang.


发件人: Dieter Werthmüller
发送时间: 2022年9月15日 2:42
收件人: emsig/empymod
抄送: Zhengguang Liu; Author
主题: Re: [emsig/empymod] How to calculate other EM components (Issue #169)

Hi Zhengguang. It appears to me that you mix things from empymod.dipole and empymod.bipole. The ab-parameter is only for the dipole function. Please have a look at the relevant documentation:
• https://empymod.emsig.xyz/en/stable/api/empymod.model.dipole.html
• https://empymod.emsig.xyz/en/stable/api/empymod.model.bipole.html
So ab=41 has no effect. It is not a problem, but you see a warning that this parameter is not used.
More importantly, the configuration you are trying to compute yields in a zero field (x-directed electric dipole measured with inline x-directed magnetic receivers), see https://empymod.emsig.xyz/en/stable/gallery/fdomain/src_rec_comparison.html : Your configuration corresponds loosely to the fourth row, first column: The field along the x-axis is zero.
