### ISSUE TITLE
Announcement: Julia wrapper for empymod

### ISSUE THREAD

**Issue by ruboerner** [emsig/empymod#214]
Hello everyone,

I'm glad to announce a simple Julia wrapper which aims to make `empymod` available in a [Julia](https://julialang.org) language environment.

### Installation
You can easily clone the repository https://github.com/ruboerner/EmpymodWrapper.jl from inside Julia:
```
using Pkg
Pkg.clone("https://github.com/ruboerner/EmpymodWrapper.jl")
```
### Basic usage
```
using EmpymodWrapper

hz = empymod_loop(
        src=[0, 0, 0, 0, 90],
        rec=[offset, 0, 0, 0, 90],
        depth=0, res=[2e14, 100], freqtime=1e-3, verb=0)
```
### Feedback
If you encounter any issues or have any questions, please feel free to open an issue on https://github.com/ruboerner/EmpymodWrapper.jl.

I hope you find `EmpymodWrapper` useful.

Best regards,
Ralph
https://github.com/ruboerner

**Comment by prisae** [comment]
Hi @ruboerner - this is cool, great!

Can I add your instructions to the empymod manual, for greater visibility?

**Comment by prisae** [comment]
Great, I will probably add it to the README and the Installation instructions in the manual. I will let you know when I have it.

Btw, I'd be happy to add you to the emsig-Github-org as developer/maintainer, and you could have the EmpymodWrapper.jl here on https://github.com/emsig/EmpymodWrapper.jl. - But on your site is just as good of course, just as a suggestion.

**Comment by prisae** [comment]
I just added the Julia Wrapper in two places:

- the [README](https://github.com/emsig/empymod#readme)
  ![Screenshot from 2024-06-25 16-28-38](https://github.com/emsig/empymod/assets/8020943/62075507-bbdf-4c2b-974c-65030dcce1c6)
- and the [installation instructions](https://empymod.emsig.xyz/en/latest/manual/installation.html) in the maunal
  ![Screenshot from 2024-06-25 16-35-21](https://github.com/emsig/empymod/assets/8020943/d163c95e-1a3a-4780-aefb-bc6e273c5cbd)

I will therefore close this issue for now. Thanks again @ruboerner !

**Comment by prisae** [comment]
(Made a small release with this, `empymod v2.3.1 - Julia wrapper`.)
